title:              The Business Copilot
email:              paul.delport@outlook.com
description:        Business automation insights with Power Platform and Azure AI
author:             Paul Delport
baseurl:            "" # leave blank because you're hosting at the root
url:                "https://Paul-Delport-001.github.io"

# Social Profiles
twitter_username:   pauldelport
github_username:    Paul_Delport-001
linkedin_username:  paul-delport

# Google Analytics (optional)
google_analytics:   UA-XXXXXXXXX-X

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
